config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :views
  #resources :moods
  devise_for :users
  root to: "home#index"
  resources :users do
    resources :moods, shallow: true
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mood.rb
class Mood < ApplicationRecord
  belongs_to :user
  validates :vibe, presence: true
  validates :health, presence: true
  validates :fun, presence: true
  validates :productivity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :moods
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
       user_moods_path(current_user)
    end
    def after_sign_out_path_for(resource)
        root_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  #before_action :set_mood, only: %i[ index show new create edit update destroy ]
  before_action :authenticate_user!
  # GET /moods or /moods.json
  def index
    @moods = current_user.moods.all
  end

  # GET /moods/1 or /moods/1.json
  def show
    @mood = current_user.moods.find(params[:id])
  end

  # GET /moods/new
  def new
    @mood = current_user.moods.build
  end

  # GET /moods/1/edit
  def edit
    @mood = current_user.moods.find(params[:id])
  end

  # POST /moods or /moods.json
  def create
    @mood = current_user.moods.build(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to mood_url(@mood), notice: "Mood was successfully created." }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1 or /moods/1.json
  def update
    @mood = current_user.moods.find(params[:id])
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to mood_url(@mood), notice: "Mood was successfully updated." }
        format.json { render :show, status: :ok, location: @mood }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1 or /moods/1.json
  def destroy
    @mood = current_user.moods.find(params[:id])
    @mood.destroy

    respond_to do |format|
      format.html { redirect_to moods_url, notice: "Mood was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = current_user.moods
    end

    # Only allow a list of trusted parameters through.
    def mood_params
      params.require(:mood).permit(:vibe, :health, :productivity, :fun, :notes, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<p>Please sign in to begin!</p>
<% if user_signed_in? %>
<%= link_to 'Go to my Moods', user_moods_path(current_user) %>
<% else %>
<%= link_to 'Register', new_user_registration_path %>
<%= link_to 'Sign In', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daily Mood Logger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render 'shared/navbar' %>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   <div>
    <% name = current_user.present? ? current_user.email : 'Stranger' %>
    <h4>Welcome, <%= name %> </h4>
    <hr>
   </div>
    <%= yield %>
  </body>
</html>

app/views/moods/_form.html.erb
<%= form_with model: mood do |form| %>
  <% if mood.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mood.errors.count, "error") %> prohibited this mood from being saved:</h2>

      <ul>
        <% mood.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :vibe, style: "display: block" %>
    <%= form.label :vibe, "Good:" %>
    <%= form.radio_button :vibe, "Good" %>
    <%= form.label :vibe, "Okay:" %>
    <%= form.radio_button :vibe, "Okay" %>
    <%= form.label :vibe, "Bad:" %>
    <%= form.radio_button :vibe, "Bad" %>
  </div>

  <div>
    <%= form.label :health, style: "display: block" %>
    <%= form.label :health, "Good:" %>
    <%= form.radio_button :health, "Good" %>
    <%= form.label :health, "Okay:" %>
    <%= form.radio_button :health, "Okay" %>
    <%= form.label :health, "Bad:" %>
    <%= form.radio_button :health, "Bad" %>
  </div>

  <div>
    <%= form.label :productivity, style: "display: block" %>
    <%= form.label :productivity, "Good:" %>
    <%= form.radio_button :productivity, "Good" %>
    <%= form.label :productivity, "Okay:" %>
    <%= form.radio_button :productivity, "Okay" %>
    <%= form.label :productivity, "Bad:" %>
    <%= form.radio_button :productivity, "Bad" %>
  </div>

  <div>
    <%= form.label :fun, style: "display: block" %>
    <%= form.label :fun, "Good:" %>
    <%= form.radio_button :fun, "Good" %>
    <%= form.label :fun, "Okay:" %>
    <%= form.radio_button :fun, "Okay" %>
    <%= form.label :fun, "Bad:" %>
    <%= form.radio_button :fun, "Bad" %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.label :notes, "Additional thoughts or feelings?" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/moods/_mood.html.erb
<div id="<%= dom_id mood %>">
  <p>
  <strong>Date created:</strong>
  <%= mood.created_at %>
  </p>
    <strong>Vibe:</strong>
    <%= mood.vibe %>
  </p>

  <p>
    <strong>Health:</strong>
    <%= mood.health %>
  </p>

  <p>
    <strong>Productivity:</strong>
    <%= mood.productivity %>
  </p>

  <p>
    <strong>Fun:</strong>
    <%= mood.fun %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= mood.notes %>
  </p>
</div>

app/views/moods/_newform.html.erb
<%= form_with model: [ current_user, current_user.moods.build] do |form| %>
  <% if mood.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mood.errors.count, "error") %> prohibited this mood from being saved:</h2>

      <ul>
        <% mood.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :vibe, style: "display: block" %>
    <%= form.label :vibe, "Good:" %>
    <%= form.radio_button :vibe, "Good" %>
    <%= form.label :vibe, "Okay:" %>
    <%= form.radio_button :vibe, "Okay" %>
    <%= form.label :vibe, "Bad:" %>
    <%= form.radio_button :vibe, "Bad" %>
  </div>

  <div>
    <%= form.label :health, style: "display: block" %>
    <%= form.label :health, "Good:" %>
    <%= form.radio_button :health, "Good" %>
    <%= form.label :health, "Okay:" %>
    <%= form.radio_button :health, "Okay" %>
    <%= form.label :health, "Bad:" %>
    <%= form.radio_button :health, "Bad" %>
  </div>

  <div>
    <%= form.label :productivity, style: "display: block" %>
    <%= form.label :productivity, "Good:" %>
    <%= form.radio_button :productivity, "Good" %>
    <%= form.label :productivity, "Okay:" %>
    <%= form.radio_button :productivity, "Okay" %>
    <%= form.label :productivity, "Bad:" %>
    <%= form.radio_button :productivity, "Bad" %>
  </div>

  <div>
    <%= form.label :fun, style: "display: block" %>
    <%= form.label :fun, "Good:" %>
    <%= form.radio_button :fun, "Good" %>
    <%= form.label :fun, "Okay:" %>
    <%= form.radio_button :fun, "Okay" %>
    <%= form.label :fun, "Bad:" %>
    <%= form.radio_button :fun, "Bad" %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.label :notes, "Additional thoughts or feelings?" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/moods/edit.html.erb
<h1>Editing mood</h1>

<%= render "form", mood: @mood %>

<br>

<div>
  <%= link_to "Show this mood", @mood %> |
  <%= link_to "Back to moods", user_moods_path(current_user) %>
</div>

app/views/moods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Moods</h1>

<div id="moods">
  <% current_user.moods.each do |mood| %>
    <li>
      <%= link_to mood.created_at, mood_path(mood) %>
    </li>
  <% end %>
</div>

<%= link_to "New mood", new_user_mood_path %>

app/views/moods/new.html.erb
<h1>New mood</h1>

<%= render "newform",  mood: @mood %>

<br>

<div>
  <%= link_to "Back to moods", user_moods_path(current_user) %>
</div>

app/views/moods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mood %>

<div>
  <%= link_to "Edit this mood", edit_mood_path(@mood) %> |
  <%= link_to "Back to moods", user_moods_path(current_user) %>

  <%= button_to "Destroy this mood", @mood, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Daily Mood Logger</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
  </div>
</nav>